//created on: 03-Jul-2019
package com.drool_issue.rules

import com.drool_issue.domain.SampleDomain;
import com.drool_issue.util.CoreUtils;



rule "rule 1.1"
  when
    $sampleDomain: SampleDomain(instanceVariable2 == "Value of instance variable")
  then
    System.out.println("Rule 1.1 fired");
    modify($sampleDomain){
    		setInstanceVariable1(3)
    }
end

rule "rule 1.2"
  when
    $sampleDomain: SampleDomain(getAnotherFunction($sampleDomain) == this)
  then
    System.out.println("Rule 1.2 fired");
    modify($sampleDomain){
    		setInstanceVariable1(3)
    }
end










