//created on: 03-Jul-2019
package com.drool_issue.rules

import com.drool_issue.domain.SampleDomain;
import com.drool_issue.util.CoreUtils;



rule "rule 1.1"
  when
    $sampleDomain: SampleDomain(instanceVariable2 == "Value of instance variable")
  then
    System.out.println("Rule 1.1 fired");
    modify($sampleDomain){
    		setInstanceVariable1(3)
    }
end

rule "rule 1.2"
  when
    $sampleDomain: SampleDomain(CoreUtils.anotherFunction())
  then
    System.out.println("Rule 1.2 fired");
    modify($sampleDomain){
    		setInstanceVariable1(3)
    }
end

rule "rule 1.3"
  when
    $sampleDomain: SampleDomain(CoreUtils.anotherFunction($sampleDomain))
  then
    System.out.println("Rule 1.3 fired");
    modify($sampleDomain){
    		setInstanceVariable3(4)
    }
end



rule "rule 1.4"
  when
    $sampleDomain: SampleDomain(anotherFunction())
  then
    System.out.println("Rule 1.4 fired");
    modify($sampleDomain){
    		setInstanceVariable1(3)
    }
end


rule "rule 1.5"
  when
    $sampleDomain: SampleDomain(anotherFunction($sampleDomain))
  then
    System.out.println("Rule 1.5 fired");
    modify($sampleDomain){
    		setInstanceVariable3(4)
    }
end







